# Generated by Django 2.0.7 on 2019-08-31 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('person', models.CharField(max_length=10, verbose_name='No. of persons')),
                ('date', models.CharField(max_length=12)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
    ]
