# Generated by Django 2.0.7 on 2019-09-01 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_category_meal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
